// Code generated by protoc-gen-go. DO NOT EDIT.
//
// Vendored from github.com/SagerNet/sing-box at tag v1.13.14,
// experimental/v2rayapi/stats_grpc.pb.go, with only these changes:
//   - the package clause renamed to this package
//   - server-side symbols removed (we are a client)
//
// sing-box is licensed under GPL-3.0-or-later with an additional Anti-QUIC-Blocking
// clause; see https://github.com/SagerNet/sing-box/blob/main/LICENSE
//
// Regenerate with `protoc --go_out=. --go-grpc_out=. stats.proto` against
// experimental/v2rayapi/stats.proto (1.1 KB) if the upstream API ever changes.
//
// Importing github.com/sagernet/sing-box/experimental/v2rayapi directly would also
// work — that package carries no build tag — but it drags in gvisor, quic-go and the
// rest of the sing-box dependency graph for two request types.

package v2rayapi

import (
	context "context"

	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// ServiceName is the gRPC service sing-box actually registers.
//
// NOT the name protoc generated from `package experimental.v2rayapi`. sing-box overrides
// it at init time, in experimental/v2rayapi/stats.go:
//
//	func init() {
//		StatsService_ServiceDesc.ServiceName = "v2ray.core.app.stats.command.StatsService"
//	}
//
// so that existing v2ray tooling can talk to it. That rename lives in a hand-written file
// alongside the generated ones, so vendoring only the generated code — as this package
// does — silently misses it, and every call comes back
//
//	rpc error: code = Unimplemented desc = unknown service experimental.v2rayapi.StatsService
//
// If these files are ever re-vendored, protoc's names will come back and this has to be
// re-applied. TestServiceNameMatchesSingBox guards against exactly that.
const ServiceName = "v2ray.core.app.stats.command.StatsService"

const (
	StatsService_GetStats_FullMethodName    = "/" + ServiceName + "/GetStats"
	StatsService_QueryStats_FullMethodName  = "/" + ServiceName + "/QueryStats"
	StatsService_GetSysStats_FullMethodName = "/" + ServiceName + "/GetSysStats"
)

// StatsServiceClient is the client API for StatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatsServiceClient interface {
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
	QueryStats(ctx context.Context, in *QueryStatsRequest, opts ...grpc.CallOption) (*QueryStatsResponse, error)
	GetSysStats(ctx context.Context, in *SysStatsRequest, opts ...grpc.CallOption) (*SysStatsResponse, error)
}

type statsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatsServiceClient(cc grpc.ClientConnInterface) StatsServiceClient {
	return &statsServiceClient{cc}
}

func (c *statsServiceClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, StatsService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) QueryStats(ctx context.Context, in *QueryStatsRequest, opts ...grpc.CallOption) (*QueryStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryStatsResponse)
	err := c.cc.Invoke(ctx, StatsService_QueryStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetSysStats(ctx context.Context, in *SysStatsRequest, opts ...grpc.CallOption) (*SysStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SysStatsResponse)
	err := c.cc.Invoke(ctx, StatsService_GetSysStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
